-- CreateTable
CREATE TABLE "Receipt" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "customerOrganization" TEXT NOT NULL,
    "customerName" TEXT,
    "customerEmail" TEXT,
    "clientContacts" JSONB,
    "additionalNames" JSONB,
    "additionalEmails" JSONB,
    "projectName" TEXT NOT NULL,
    "serviceType" TEXT NOT NULL,
    "projectStartDate" TIMESTAMP(3) NOT NULL,
    "projectEndDate" TIMESTAMP(3) NOT NULL,
    "description" TEXT,
    "projectTotal" DOUBLE PRECISION NOT NULL,
    "amountPaid" DOUBLE PRECISION NOT NULL,
    "remainingBalance" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL,
    "paymentMethod" TEXT NOT NULL,
    "bankName" TEXT,
    "bankAccountNumber" TEXT,
    "cardNumber" TEXT,
    "mobileMoneyProvider" TEXT,
    "mobileNumber" TEXT,
    "countryCode" TEXT,
    "companyName" TEXT,
    "companyEmail" TEXT,
    "companyLogo" TEXT,
    "companyContacts" JSONB,

    CONSTRAINT "Receipt_pkey" PRIMARY KEY ("id")
);
